services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: code/lambda_function.py
      FLASK_RUN_HOST: 0.0.0.0
