AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A serverless application for polynomial regression.

Parameters:
  PythonRuntime:
    Type: String
    Default: python3.9
    AllowedValues:
      - python3.9
      - python3.10
      - python3.11
      - python3.12
    Description: Python runtime version for Lambda functions and layers

Globals:
  Function:
    Runtime: !Ref PythonRuntime
    Timeout: 30
    MemorySize: 256

Resources:
  RegressionAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: MyPolynomialApi
      CorsConfiguration:
        AllowMethods: ['POST']
        AllowOrigins: ['*']

  PythonDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./layers/python/
      CompatibleRuntimes:
        - !Ref PythonRuntime
    DeletionPolicy: Delete
    Metadata:
      BuildMethod: !Ref PythonRuntime

  LinearFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: lambda_function.handler
      Layers:
        - !Ref PythonDependencies
      Events:
        LinearEndpoint:
          Type: HttpApi
          Properties:
            Path: /linear
            Method: POST
            ApiId: !Ref RegressionAPI
    Metadata:
      BuildMethod: !Ref PythonRuntime

  QuadraticFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: lambda_function.handler
      Layers:
        - !Ref PythonDependencies
      Events:
        QuadraticEndpoint:
          Type: HttpApi
          Properties:
            Path: /quadratic
            Method: POST
            ApiId: !Ref RegressionAPI
    Metadata:
      BuildMethod: !Ref PythonRuntime
